/*
 * Spider Framework
 * 
 * Copyright (c) 2006-2007 ServerSide Corp. All Rights Reserved.
 * 
 * 본 소스 및 바이너리 파일에 대한 권한은 모두 ServerSide 에 있습니다.
 * 저작자와의 협의 없이 수정 및 무단 배포를 금합니다.
 */

package test.uuid;

import java.security.SecureRandom;
import java.util.Random;

import nebsoa.common.util.FormatUtil;

/*******************************************************************
 * <pre>
 * 1.설명 
 * Apache-AXIS 에서 사용하는 UUID generator 를 가져옴.
 * 아래는 Apache-AXIS 에 설명되어 있는 내용이다.
 * 
 * Creates time-based UUID's. See the <a href="http://www.ietf.org/internet-drafts/draft-mealling-uuid-urn-03.txt">UUID Internet Draft</a> for details.
 * 
 * 2.사용법
 * 
 * <font color="red">
 * 3.주의사항
 * </font>
 *
 * @author $Author: cvs $
 * @version
 *******************************************************************
 * - 변경이력 (버전/변경일시/작성자)
 * 
 * $Log: FastUUIDGen.java,v $
 * Revision 1.1  2018/01/15 03:39:50  cvs
 * *** empty log message ***
 *
 * Revision 1.1  2016/04/15 02:22:44  cvs
 * neo cvs init
 *
 * Revision 1.1  2011/07/01 02:13:51  yshong
 * *** empty log message ***
 *
 * Revision 1.1  2008/11/18 11:27:24  김성균
 * *** empty log message ***
 *
 * Revision 1.1  2008/11/18 11:01:27  김성균
 * LGT Gateway를 위한 프로젝트로 분리
 *
 * Revision 1.1  2008/08/04 08:54:55  youngseokkim
 * *** empty log message ***
 *
 * Revision 1.2  2008/02/20 00:42:48  오재훈
 * *** empty log message ***
 *
 * Revision 1.1  2007/11/26 08:38:55  안경아
 * *** empty log message ***
 *
 * Revision 1.1  2006/11/21 05:50:22  이종원
 * *** empty log message ***
 *
 * Revision 1.2  2006/06/17 10:37:45  김성균
 * *** empty log message ***
 *
 * </pre>
 ******************************************************************/
public class FastUUIDGen implements UUIDGen {
	
    private static Random secureRandom;

    private static String nodeStr;
    private static int clockSequence;

    private long lastTime = 0;

    static {
        // problem: the node should be the IEEE 802 ethernet address, but can not
        // be retrieved in Java yet.
        // see bug ID 4173528
        // workaround (also suggested in bug ID 4173528)
        // If a system wants to generate UUIDs but has no IEE 802 compliant
        // network card or other source of IEEE 802 addresses, then this section
        // describes how to generate one.
        // The ideal solution is to obtain a 47 bit cryptographic quality random
        // number, and use it as the low 47 bits of the node ID, with the most
        // significant bit of the first octet of the node ID set to 1. This bit
        // is the unicast/multicast bit, which will never be set in IEEE 802
        // addresses obtained from network cards; hence, there can never be a
        // conflict between UUIDs generated by machines with and without network
        // cards.
        try {
            secureRandom = SecureRandom.getInstance("SHA1PRNG", "SUN");
        } catch (Exception e) {
            secureRandom = new Random();
        }//end try catch

        nodeStr = getNodeHexValue();
        clockSequence = getClockSequence();
    }//end of static

    private static String getNodeHexValue() {
        long node = 0;
        long nodeValue = 0;
        while ( (node = getBitsValue(nodeValue, 47, 47)) == 0 ) {
            nodeValue = secureRandom.nextLong();
        }//end while
        node = node | 0x800000000000L;
        return FormatUtil.lPadding(Long.toHexString(node), 12, '0');
    }//end of getNodeHexValue()

    private static int getClockSequence() {
        return secureRandom.nextInt(16384);
    }//end of getClockSequence()

	/**
	 * UUID 를 리턴합니다.
	 * 
	 * @return 생성된 uuid
	 * @see test.uuid.UUIDGen#nextUUID()
	 */
	public String nextUUID() {
        long time = System.currentTimeMillis();

        long timestamp = time * 10000;
        timestamp += 0x01b21dd2L << 32;
        timestamp += 0x13814000;
        
        synchronized(this) {
            if (time - lastTime <= 0) {
                clockSequence = ((clockSequence + 1) & 16383);
            }//end if
            lastTime = time;
        }//end synchronized

        long timeLow = getBitsValue(timestamp, 32, 32);
        long timeMid = getBitsValue(timestamp, 48, 16);
        long timeHi = getBitsValue(timestamp, 64, 16) | 0x1000;

        long clockSeqLow = getBitsValue(clockSequence, 8, 8);
        long clockSeqHi = getBitsValue(clockSequence, 16, 8) | 0x80;
        
        String timeLowStr = FormatUtil.lPadding(Long.toHexString(timeLow), 8, '0');
        String timeMidStr = FormatUtil.lPadding(Long.toHexString(timeMid), 4, '0');
        String timeHiStr = FormatUtil.lPadding(Long.toHexString(timeHi), 4, '0');

        String clockSeqHiStr = FormatUtil.lPadding(Long.toHexString(clockSeqHi), 2, '0');
        String clockSeqLowStr = FormatUtil.lPadding(Long.toHexString(clockSeqLow), 2, '0');

        StringBuffer result = new StringBuffer(36);
        result.append(timeLowStr).append("-");
        result.append(timeMidStr).append("-");
        result.append(timeHiStr).append("-");
        result.append(clockSeqHiStr).append(clockSeqLowStr);
        result.append("-").append(nodeStr);

        return result.toString();
	}//end of nextUUID()
	
    private static long getBitsValue(long value, int startBit, int bitLen) {
        return ((value << (64-startBit)) >>> (64-bitLen));
    }//end of getBitsValue()
    
    
	/*----------------------------------
	 * 
	 * 테스트 코드가 포함된 main() 메소드
	 * 
	 ----------------------------------*/
    
    public static void main(String [] args) {
    	for (int i = 0; i < 100; i++) {
    		String uuid = new FastUUIDGen().nextUUID();
    		System.out.println(uuid + "\t:\tlength=" + uuid.length());
    	}//end for
    }//end of main()

}// end of FastUUIDGen.java